name: Main
on: workflow_dispatch
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        uses: ianwalter/puppeteer
        with:
          args: yarn
      - name: Run
        uses: ianwalter/puppeteer
        with:
          args: yarn start