name: Main
on: workflow_dispatch
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        uses: ianwalter/puppeteer@v4.0.0
        with:
          args: yarn
      - name: Run Browser
        uses: ianwalter/puppeteer@v4.0.0
        with:
          args: yarn start
        env:
          MECKANO_USER: ${{ secrets.MECKANO_USER }}
          MECKANO_PASS: ${{ secrets.MECKANO_PASS }}